title: Igor M. Araújo # your name (or website title) here
logo: "/images/DSC_7053.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>Ph. D. candidate at Electrical Engineering Graduate Program (PPGEE) of Federal University of Pará (UFPA), Brazil, with an emphasis in Applied Computing. Nowadays, he is affiliated to computational intelligence and operational research laboratory  (LINC) at UFPA. His research interests include computational intelligence, data mining and parallel computing using GPGPU.<\p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
