title: Igor M. Araújo # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph. D. candidate at Electrical Engineering Graduate Program (PPGEE) of Federal University of Pará (UFPA), Brazil, with an emphasis in Applied Computing. He received master's in Applied Computing for Electric Engineering from the Federal University of Pará (UFPA) in 2017 and bachelor's degree in computer engineering from Institute of Superior Studies of Amazon (IESAM), Brazil in 2014. Nowadays, he is affiliated to computational intelligence and operational research laboratory  (LINC) at UFPA. His research interests include computational intelligence, data mining and parallel computing using GPGPU.
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
